# FRONT-END
# - SOCKET.IO (CHAT CLIENTE E ATENDENTE)
# - DARK-MODE/LIGHT-MODE
# - PAPIRAR NO REACT

# BACK-END
# - CRIAR PRODUTO | EDITAR PRODUTO | REMOVER PRODUTO | LISTAR PRODUTOS | PESQUISAR PRODUTOS
# - PRODUTO (NOME, VALOR, DESCRIÇÃO, ESTOQUE)
# - IMAGENS APONTADO PARA ALGUM STORAGE EX.: AWS S3
# - PAINEL ADMIN (CADASTRAR, EDITAR PRODUTOS E CLIENTES)
# - USUÁRIO (ADMIN, NORMAL)
# - ROTA DE LEITURA E ESCRITA DE ARQUIVOS
# - ROTA DE ARQUIVOS ESTÁTICOS
# - TESTES
# - AUTENTICAÇÃO JWT
# - CAMADAS MSC
# - IMPLEMENTAR MIDDLEWARES
# - ROUND 3 (JWT, POO, TS, SOLID,)
# - CONFIGURAR LINT