version: '3'
services:
  # 3 - FRONT-END
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
    restart: always
    depends_on:
      - backend

  # 2 - BACK-END
  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/backend
    restart: always
    depends_on:
      - database

  # 1 - DATABASE
  database:
    container_name: app_database
    build: ./database
    # image: mysql:8.4.2
    ports:
      - "3306:3306"
    # environment:
      # - MYSQL_USER=admin
      # - MYSQL_PASSWORD=1234
      # - MYSQL_ROOT_PASSWORD=123456
      # - MYSQL_DATABASE=kabrum
    restart: always
    healthcheck: # DEVE AGUARDAR O BANCO DE DADOS FICAR OPERACIONAL
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5