INSERT INTO
    users (
        first_name,
        last_name,
        email,
        cpf,
        address_id
    )
VALUES (
        'João',
        'Silva',
        'joao.silva@example.com',
        '12345678901',
        1
    ),
    (
        'Maria',
        'Oliveira',
        'maria.oliveira@example.com',
        '23456789012',
        2
    ),
    (
        'Carlos',
        'Santos',
        'carlos.santos@example.com',
        '34567890123',
        3
    ),
    (
        'Ana',
        'Costa',
        'ana.costa@example.com',
        '45678901234',
        4
    ),
    (
        'Pedro',
        'Lima',
        'pedro.lima@example.com',
        '56789012345',
        5
    );